### PR TITLE
(MODULES-7153) - Update release checks to run against ruby 2.4.1 and unmanage gitlabs-ci.yml

### PR DESCRIPTION
**Pull request by pmcmaw**

### CODE REVIEW

**Comment by david22swan** [comment]
Appveyor test's have been removed. Was this intentional???

**Comment by pmcmaw** [comment]
@david22swan they have only been removed from `.sync.yml` they exist in the config_defaults so are being duplicated here: https://github.com/puppetlabs/pdk-templates/blob/master/config_defaults.yml#L60:L82

**Comment by david22swan** [comment]
Their not running against commits though. Thought that might be an error

**Comment by pmcmaw** [comment]
So appveyor has never been enabled on this repo (see this PR: https://github.com/puppetlabs/puppetlabs-bootstrap/pull/19) you will notice it hasn't ran it either. 

It not running is not related to my PR.

**Comment by david22swan** [comment]
Ah nvm then.

**Pull request merged**
